spring:
  application:
    name: BaiDUFaceReg
  # 数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/baiduai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# mybatis
mybatis:
  mapper:
    locations: classpath:com/hj/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  oss:
    bucket-name: com-hj-web-framework
    access-key-secret: ***
    access-key-id: ***
    endpoint: https://oss-cn-shanghai.aliyuncs.com
